databases:
  - name: doctor_app
    databaseName: doctor_app_ddn1
    user: doctor_app_ddn1_user

services:
  - type: web
    name: doc_app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: doctor_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false