databases:
  - name: doc_app
    databaseName: doc_app
    user: doc_app

services:
  - type: web
    name: doc_app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: doc_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false